// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnxCgJZ8ILEAmCOTjjm1uhztozV5wtg8E',
    appId: '1:871413586148:web:bbd6fa7d1f4e1904d6b4f1',
    messagingSenderId: '871413586148',
    projectId: 'envanter-yonetim-uygulamasi',
    authDomain: 'envanter-yonetim-uygulamasi.firebaseapp.com',
    storageBucket: 'envanter-yonetim-uygulamasi.firebasestorage.app',
    measurementId: 'G-1WP4T86ZG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoQcbmX0p8hp8sU2UJcipl6yRvsgHAWqc',
    appId: '1:871413586148:android:bc773e5003e37576d6b4f1',
    messagingSenderId: '871413586148',
    projectId: 'envanter-yonetim-uygulamasi',
    storageBucket: 'envanter-yonetim-uygulamasi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgKRdjqc_uDqGAc3DkNS-feY31kDVSEHs',
    appId: '1:871413586148:ios:badaf623aa2cafd1d6b4f1',
    messagingSenderId: '871413586148',
    projectId: 'envanter-yonetim-uygulamasi',
    storageBucket: 'envanter-yonetim-uygulamasi.firebasestorage.app',
    iosBundleId: 'com.example.envanterapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgKRdjqc_uDqGAc3DkNS-feY31kDVSEHs',
    appId: '1:871413586148:ios:badaf623aa2cafd1d6b4f1',
    messagingSenderId: '871413586148',
    projectId: 'envanter-yonetim-uygulamasi',
    storageBucket: 'envanter-yonetim-uygulamasi.firebasestorage.app',
    iosBundleId: 'com.example.envanterapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnxCgJZ8ILEAmCOTjjm1uhztozV5wtg8E',
    appId: '1:871413586148:web:b8a0e9f654af3459d6b4f1',
    messagingSenderId: '871413586148',
    projectId: 'envanter-yonetim-uygulamasi',
    authDomain: 'envanter-yonetim-uygulamasi.firebaseapp.com',
    storageBucket: 'envanter-yonetim-uygulamasi.firebasestorage.app',
    measurementId: 'G-SQMF82EGXL',
  );
}
